name: Asset Release Workflow

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: ðŸ‘‰ Checkout code
        uses: actions/checkout@v4

      # 2. Build release package using the build script
      - name: ðŸ“¦ Build release package
        run: |
          chmod +x bin/build-release.sh
          ./bin/build-release.sh

      # 3. Upload the zipped project as a release asset
      - name: ðŸ“¤ Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: customs-fees-for-woocommerce.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4. All good
      - name: ðŸŽ‰ All good
        run: echo "All good!"
